export interface OfferLetterInteractiveStateInterfaceModel {
  candidateName: string;
  setCandidateName: (val: string) => void;
  candidateEmail: string;
  setCandidateEmail: (val: string) => void;
  candidateAddress: string;
  setCandidateAddress: (val: string) => void;
  candidatePhone: string;
  setCandidatePhone: (val: string) => void;
  candidateDob: string;
  setCandidateDob: (val: string) => void;
  jobTitle: string;
  setJobTitle: (val: string) => void;
  department: string;
  setDepartment: (val: string) => void;
  annualSalary: string;
  setAnnualSalary: (val: string) => void;
  reportingManager: string;
  setReportingManager: (val: string) => void;
  probationMonths: number;
  setProbationMonths: (val: number) => void;
  joiningDate: string;
  setJoiningDate: (val: string) => void;
  workLocation: string;
  setWorkLocation: (val: string) => void;
  equity: string;
  setEquity: (val: string) => void;
  signOnBonus: string;
  setSignOnBonus: (val: string) => void;
  companyName: string;
  setCompanyName: (val: string) => void;
  companyAddress: string;
  setCompanyAddress: (val: string) => void;
  signatureCount: 2 | 3;
  setSignatureCount: (val: 2 | 3) => void;
  directorName: string;
  setDirectorName: (val: string) => void;
  directorTitle: string;
  setDirectorTitle: (val: string) => void;
  directorEmail: string;
  setDirectorEmail: (val: string) => void;
  hrHeadName: string;
  setHrHeadName: (val: string) => void;
  hrHeadEmail: string;
  setHrHeadEmail: (val: string) => void;
  ctoName: string;
  setCtoName: (val: string) => void;
  ctoEmail: string;
  setCtoEmail: (val: string) => void;
  errors?: Record<string, string>;
}

export default OfferLetterInteractiveStateInterfaceModel;
